### ISSUE TITLE
What is the `mainRunner` project for?

### ISSUE THREAD

**Issue by fluency03** [tillrohrmann/flink-project#4]
I would like to know why you have a `root` project and a `mainRunner` project.   What is the `mainRunner` project for?

**Comment by tillrohrmann** [comment]
The `mainRunner` project simply sets the provided dependencies to non-provided dependencies. Otherwise you wouldn't be able to run the project from within IntelliJ.

**Comment by fluency03** [comment]
But from my IntelliJ, I see no difference. Just two same sbt projects with different names.

![image](https://user-images.githubusercontent.com/7440735/32080100-1814b922-baae-11e7-9209-f2bbc8d12e46.png)

After removing the idea.sbt file, I see no impact, there is still this root project and it is having all the dependencies. 

![image](https://user-images.githubusercontent.com/7440735/32080186-95c649c6-baae-11e7-9a3b-dfac26854df6.png)

**Comment by fluency03** [comment]
And in the "Use classpath of module" I can select the module "root".

**Comment by tillrohrmann** [comment]
I think they look the same because you don't look at the `mainRunner` dependencies. Just try to run the project code from IntelliJ and you will see that it does not run because of the missing dependencies. If you set the classpath module to `mainRunner`, then it will.

**Comment by fluency03** [comment]
Thanks.   I will try what you said.

**Comment by fluency03** [comment]
Hi @tillrohrmann , I have another question. 

When you want to deploy the jobs to Flink, you have to submit the each of the job as a JAR.

Now, I have several different jobs under the module: `org.example`:
- `WordCount`
- `SocketTextStreamWordCount`
- `WikipediaEditMonitoring`
- etc...

My question is: how to package the jobs to each of their separate JARs, so that I can submit the jobs to Fink separately, like:
- `WordCount.jar`
- `SocketTextStreamWordCount.jar`
- `WikipediaEditMonitoring.jar`
- etc...

More specifically, how to configure the `build.sbt` or set up the sbt project structure?

Many Thanks.

**Comment by tillrohrmann** [comment]
Hi, I think for this you use the sbt-assembly plugin. Here is the documentation of this plugin: https://github.com/sbt/sbt-assembly.

**Comment by tillrohrmann** [comment]
Issue seems to be resolved.
